<?php

namespace Database\Seeders;

use App\Models\Destination;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get admin user or create one for destinations
        $adminUser = User::where('email', 'admin@wellawaya.com')->first();
        
        if (!$adminUser) {
            $adminUser = User::first();
        }

        if (!$adminUser) {
            $this->command->warn('No user found. Please run AdminSeeder first.');
            return;
        }

        $destinations = [
            [
                'name' => 'Bambarakanda Falls',
                'slug' => 'bambarakanda-falls',
                'description' => 'Bambarakanda Falls is the highest waterfall in Sri Lanka, standing at an impressive 263 meters (863 feet). Located in the Badulla District, this magnificent waterfall cascades down a rocky cliff surrounded by lush green forests. The waterfall is part of the Walawe River and creates a spectacular sight, especially during the monsoon season when the water flow is at its peak.',
                'location' => 'Kalupahana, Badulla District',
                'category' => 'waterfall',
                'highlights' => 'Highest waterfall in Sri Lanka (263m), Spectacular cascading water, Beautiful forest surroundings, Great for photography, Hiking trails nearby',
                'best_time_to_visit' => 'December to April (dry season) or May to September (monsoon for maximum water flow)',
                'how_to_reach' => 'From Wellawaya: Take the A4 highway towards Haputale. Turn off at Kalupahana junction and follow the signs. The waterfall is approximately 25 km from Wellawaya. You can hire a tuk-tuk or drive. The last part requires a short hike.',
                'tips' => 'Wear comfortable hiking shoes, Bring water and snacks, Best visited early morning for better lighting, Be cautious near the waterfall edge, Carry a raincoat during monsoon season',
                'latitude' => 6.7500,
                'longitude' => 80.9167,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Diyaluma Falls',
                'slug' => 'diyaluma-falls',
                'description' => 'Diyaluma Falls is the second highest waterfall in Sri Lanka, with a height of 220 meters (722 feet). This stunning waterfall is located near Koslanda and offers one of the most unique experiences - natural infinity pools at the top! The waterfall cascades in multiple tiers, creating a breathtaking natural spectacle. The upper pools are accessible via a challenging but rewarding hike.',
                'location' => 'Koslanda, Badulla District',
                'category' => 'waterfall',
                'highlights' => 'Second highest waterfall (220m), Natural infinity pools at the top, Multi-tier cascading falls, Swimming opportunities, Panoramic mountain views',
                'best_time_to_visit' => 'December to April for swimming, May to September for maximum water flow',
                'how_to_reach' => 'From Wellawaya: Take the A4 highway towards Haputale, then turn towards Koslanda. The waterfall is about 30 km from Wellawaya. A 2-3 hour hike is required to reach the top pools.',
                'tips' => 'Hike is challenging - bring proper gear, Swimming in natural pools is possible but be careful, Start early to avoid crowds, Bring plenty of water, Wear non-slip shoes',
                'latitude' => 6.7333,
                'longitude' => 81.0167,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Ravana Falls',
                'slug' => 'ravana-falls',
                'description' => 'Ravana Falls is a beautiful waterfall located near Ella, named after the legendary King Ravana from the Ramayana epic. According to mythology, this is where Ravana hid Princess Sita. The waterfall cascades down in multiple tiers, creating a picturesque scene. It\'s easily accessible and one of the most popular waterfalls in the region.',
                'location' => 'Ella, Badulla District',
                'category' => 'waterfall',
                'highlights' => 'Mythological significance, Easily accessible, Multiple cascading tiers, Popular tourist spot, Close to Ella town',
                'best_time_to_visit' => 'Year-round, but best during May to September for maximum water flow',
                'how_to_reach' => 'From Wellawaya: Take the A4 highway towards Ella. The waterfall is visible from the main road, about 6 km before Ella town. Approximately 20 km from Wellawaya.',
                'tips' => 'Can be viewed from the road, Short walk to get closer, Popular spot - visit early morning, Great for photography, Combine with Ella Rock visit',
                'latitude' => 6.8667,
                'longitude' => 81.0500,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Lipton\'s Seat',
                'slug' => 'liptons-seat',
                'description' => 'Lipton\'s Seat is a famous viewpoint where Sir Thomas Lipton, the tea magnate, used to survey his tea empire. Located at an elevation of 1,970 meters (6,463 feet), it offers breathtaking panoramic views of the surrounding tea plantations, valleys, and mountains. On a clear day, you can see up to 65 km away, including views of the Udawalawe reservoir.',
                'location' => 'Dambatenne, Haputale',
                'category' => 'viewpoint',
                'highlights' => 'Historic tea plantation viewpoint, Panoramic 360-degree views, Elevation of 1,970m, Tea factory visit nearby, Sunrise and sunset views',
                'best_time_to_visit' => 'Early morning (6-8 AM) for sunrise and clear views, or late afternoon for sunset. Avoid midday when clouds may obstruct views.',
                'how_to_reach' => 'From Wellawale: Take the A4 highway to Haputale, then follow signs to Dambatenne Tea Factory. From there, it\'s a 7 km drive or hike to Lipton\'s Seat. Total distance from Wellawaya is about 40 km.',
                'tips' => 'Best visited early morning for clear views, Bring warm clothing - it can be cold, Combine with Dambatenne Tea Factory tour, Allow 2-3 hours for the visit, Check weather before going',
                'latitude' => 6.7833,
                'longitude' => 80.9667,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Dambatenne Tea Factory',
                'slug' => 'dambatenne-tea-factory',
                'description' => 'The Dambatenne Tea Factory is a historic tea processing facility established by Sir Thomas Lipton in 1890. This working tea factory offers guided tours where visitors can learn about the entire tea production process, from leaf picking to packaging. The factory produces high-quality Ceylon tea and is surrounded by beautiful tea plantations.',
                'location' => 'Dambatenne, Haputale',
                'category' => 'factory',
                'highlights' => 'Historic tea factory (1890), Guided factory tours, Tea tasting sessions, Learn tea production process, Beautiful tea plantation views',
                'best_time_to_visit' => 'Year-round, factory tours available daily. Best time is during tea picking season (varies by elevation).',
                'how_to_reach' => 'From Wellawaya: Take the A4 highway to Haputale, then follow signs to Dambatenne. The factory is about 35 km from Wellawaya. Accessible by car or tuk-tuk.',
                'tips' => 'Guided tours available, Tea tasting included, Combine with Lipton\'s Seat visit, Photography allowed in most areas, Buy fresh tea from factory shop',
                'latitude' => 6.7833,
                'longitude' => 80.9500,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Ella Rock',
                'slug' => 'ella-rock',
                'description' => 'Ella Rock is a popular hiking destination offering spectacular views of the surrounding valleys, tea plantations, and mountains. The hike takes you through tea plantations, along railway tracks, and up to a viewpoint at approximately 1,041 meters elevation. The panoramic views from the top are absolutely stunning, making it one of the most rewarding hikes in the area.',
                'location' => 'Ella, Badulla District',
                'category' => 'mountain',
                'highlights' => 'Challenging but rewarding hike, Panoramic mountain views, Tea plantation scenery, Railway track crossing, Popular sunrise/sunset spot',
                'best_time_to_visit' => 'Early morning (start at 5-6 AM) for sunrise views, or late afternoon for sunset. Avoid midday heat.',
                'how_to_reach' => 'From Wellawaya: Drive to Ella (about 25 km). The hike starts from Ella town. Follow the railway tracks initially, then take the marked trail. Total hiking time: 3-4 hours round trip.',
                'tips' => 'Start early to avoid heat and crowds, Hire a local guide if unsure of the trail, Bring water and snacks, Wear proper hiking shoes, Allow 3-4 hours for the hike',
                'latitude' => 6.8667,
                'longitude' => 81.0500,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Nine Arch Bridge',
                'slug' => 'nine-arch-bridge',
                'description' => 'The Nine Arch Bridge, also known as the Bridge in the Sky, is a magnificent railway bridge built entirely of stone, bricks, and cement without any steel. Located between Ella and Demodara stations, this architectural marvel spans 91 meters and stands 24 meters tall. Surrounded by lush greenery, it\'s one of the most photographed locations in Sri Lanka.',
                'location' => 'Ella, Badulla District',
                'category' => 'landmark',
                'highlights' => 'Historic railway bridge (1921), No steel construction, Beautiful architecture, Surrounded by tea plantations, Train viewing opportunities',
                'best_time_to_visit' => 'Early morning (7-9 AM) or late afternoon (4-6 PM) for best lighting and train schedules. Check train timings for photo opportunities.',
                'how_to_reach' => 'From Wellawaya: Drive to Ella (25 km), then take a tuk-tuk or walk to the bridge. It\'s about 2 km from Ella town center. Accessible via a short walk through tea plantations.',
                'tips' => 'Check train schedules for photo opportunities, Best lighting in early morning, Wear comfortable walking shoes, Popular spot - visit early, Bring camera for stunning photos',
                'latitude' => 6.8500,
                'longitude' => 81.0500,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Little Adam\'s Peak',
                'slug' => 'little-adams-peak',
                'description' => 'Little Adam\'s Peak, also known as Punchi Sri Pada, is a smaller and more accessible version of the famous Adam\'s Peak. This relatively easy hike offers stunning views of Ella Gap, tea plantations, and the surrounding mountains. The peak stands at 1,141 meters and is perfect for those who want beautiful views without the strenuous climb of its larger namesake.',
                'location' => 'Ella, Badulla District',
                'category' => 'mountain',
                'highlights' => 'Easy to moderate hike, Stunning views of Ella Gap, Tea plantation scenery, Perfect for sunrise/sunset, Less crowded than Ella Rock',
                'best_time_to_visit' => 'Early morning (6-8 AM) for sunrise or late afternoon (4-6 PM) for sunset. The hike takes about 1-1.5 hours.',
                'how_to_reach' => 'From Wellawaya: Drive to Ella (25 km). The trail starts from Ella town, near the 98 Acres Resort. Well-marked path, about 1-1.5 hour hike to the top.',
                'tips' => 'Much easier than Ella Rock, Suitable for all fitness levels, Best visited for sunrise or sunset, Bring water, Allow 2-3 hours total',
                'latitude' => 6.8667,
                'longitude' => 81.0500,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Demodara Loop',
                'slug' => 'demodara-loop',
                'description' => 'The Demodara Loop is an engineering marvel where the railway track forms a complete loop, allowing the train to gain elevation while appearing to travel in a circle. The train enters a tunnel and emerges at a different level, creating a fascinating spiral railway. This unique feature was built to overcome the steep gradient in the area and is one of only a few such loops in the world.',
                'location' => 'Demodara, Badulla District',
                'category' => 'landmark',
                'highlights' => 'Unique spiral railway loop, Engineering marvel, Train viewing opportunities, Historical railway construction, Scenic location',
                'best_time_to_visit' => 'Check train schedules - best viewed when trains are passing. Early morning or afternoon trains are recommended.',
                'how_to_reach' => 'From Wellawaya: Drive towards Ella, then continue to Demodara station (about 30 km). The loop can be viewed from various viewpoints around the station area.',
                'tips' => 'Check train schedules in advance, Multiple viewpoints available, Combine with Nine Arch Bridge visit, Photography opportunities, Learn about railway history',
                'latitude' => 6.8333,
                'longitude' => 81.0333,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Uva Highlands',
                'slug' => 'uva-highlands',
                'description' => 'The Uva Highlands is a beautiful mountainous region in the Uva Province, known for its cool climate, rolling hills, tea plantations, and stunning landscapes. This region offers some of the most scenic drives in Sri Lanka, with winding roads through tea estates, misty mountains, and panoramic vistas. It\'s perfect for those seeking tranquility and natural beauty.',
                'location' => 'Uva Province (Haputale, Bandarawela, Welimada)',
                'category' => 'nature',
                'highlights' => 'Cool mountain climate, Scenic drives, Tea plantation views, Misty mountain landscapes, Peaceful atmosphere',
                'best_time_to_visit' => 'Year-round, but December to March offers the clearest views. Early morning is best for misty mountain views.',
                'how_to_reach' => 'From Wellawaya: The highlands region includes Haputale, Bandarawela, and surrounding areas. Wellawaya is part of this region. Scenic drives available on A4 and connecting roads.',
                'tips' => 'Perfect for scenic drives, Bring warm clothing, Best for photography in early morning, Explore tea plantations, Visit multiple viewpoints',
                'latitude' => 6.7667,
                'longitude' => 80.9500,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'St. Mark\'s Church',
                'slug' => 'st-marks-church',
                'description' => 'St. Mark\'s Church is a historic Anglican church located in Badulla, built during the British colonial era. This beautiful stone church features Gothic architecture and is surrounded by well-maintained gardens. It stands as a testament to the colonial history of the region and offers a peaceful place for reflection.',
                'location' => 'Badulla, Uva Province',
                'category' => 'temple',
                'highlights' => 'Historic colonial church, Gothic architecture, Beautiful stone construction, Peaceful gardens, Cultural significance',
                'best_time_to_visit' => 'Year-round during visiting hours. Sunday services available.',
                'how_to_reach' => 'From Wellawaya: Drive to Badulla town (about 15 km). The church is located in the town center, easily accessible.',
                'tips' => 'Respectful dress required, Photography allowed, Combine with Badulla town visit, Learn about colonial history, Peaceful atmosphere',
                'latitude' => 6.9931,
                'longitude' => 81.0550,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Muthiyangana Raja Maha Viharaya',
                'slug' => 'muthiyangana-temple',
                'description' => 'Muthiyangana Raja Maha Viharaya is an ancient Buddhist temple in Badulla, believed to have been visited by Lord Buddha during his third visit to Sri Lanka. This historic temple is one of the Solosmasthana (16 sacred places) in Sri Lanka and holds great religious significance. The temple features ancient stupas, beautiful murals, and a peaceful atmosphere.',
                'location' => 'Badulla, Uva Province',
                'category' => 'temple',
                'highlights' => 'Ancient Buddhist temple, One of 16 sacred places, Historical significance, Beautiful architecture, Peaceful meditation area',
                'best_time_to_visit' => 'Year-round. Early morning or evening for peaceful atmosphere. Full moon days (Poya) are special.',
                'how_to_reach' => 'From Wellawaya: Drive to Badulla town (15 km). The temple is located in the town center, easily accessible.',
                'tips' => 'Remove shoes before entering, Dress modestly, Photography may be restricted in some areas, Respectful behavior required, Learn about Buddhist history',
                'latitude' => 6.9931,
                'longitude' => 81.0550,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Buduruwagala Rock Temple',
                'slug' => 'buduruwagala-rock-temple',
                'description' => 'Buduruwagala is a 10th-century rock temple featuring seven magnificent Buddha statues carved directly into a cliff face. The site is located in a serene forest setting near Wellawaya and is famous for its 51-foot tall standing Buddha statue, the tallest ancient Buddha statue in Sri Lanka. The name "Buduruwagala" means "Buddha images carved in stone". The temple is surrounded by peaceful forest, making it an ideal place for meditation and contemplation.',
                'location' => 'Buduruwagala, 6 km southeast of Wellawaya, Monaragala District',
                'category' => 'temple',
                'highlights' => '10th-century rock carvings, 51-foot tall Buddha statue, Seven Buddha figures carved in cliff, Serene forest setting, Ancient archaeological site',
                'best_time_to_visit' => 'Early morning (6-9 AM) or late afternoon (4-6 PM) for best lighting and peaceful atmosphere. Avoid midday heat.',
                'how_to_reach' => 'From Wellawaya: Take the road towards Monaragala/Buththala. The temple is approximately 6 km southeast of Wellawaya. Well-marked and accessible by tuk-tuk or car. About 10-15 minutes drive.',
                'tips' => 'Wear modest clothing (cover shoulders and knees), Remove shoes before entering, Bring water, Best for early morning visit, Combine with other Monaragala destinations',
                'latitude' => 6.6733,
                'longitude' => 81.1283,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Maligawila Buddha Statue',
                'slug' => 'maligawila-buddha-statue',
                'description' => 'Maligawila is home to one of Sri Lanka\'s tallest free-standing Buddha statues, standing approximately 12 meters (39 feet) tall. Carved from limestone during the 7th century, this remarkable statue represents an extraordinary feat of ancient craftsmanship. The statue, along with an Avalokiteshvara (Bodhisattva) statue nearby, was discovered in 1951 and has since been restored. The site offers insights into ancient Sinhalese Buddhist art and architecture.',
                'location' => 'Maligawila, Monaragala District',
                'category' => 'temple',
                'highlights' => 'Tallest free-standing Buddha statue (12m), 7th-century limestone carving, Ancient Buddhist art, Archaeological significance, Restored historical site',
                'best_time_to_visit' => 'Early morning or late afternoon for best lighting and photography. Year-round access.',
                'how_to_reach' => 'From Wellawaya: Drive towards Monaragala, then follow signs to Maligawila. Approximately 35-40 km from Wellawaya. Accessible by car or tuk-tuk. Well-maintained roads.',
                'tips' => 'Dress modestly, Photography allowed, Learn about restoration work, Combine with other Monaragala sites, Best visited with guide for historical context',
                'latitude' => 6.8000,
                'longitude' => 81.3000,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Yudaganawa Stupa',
                'slug' => 'yudaganawa-stupa',
                'description' => 'Yudaganawa is an ancient stupa and archaeological site believed to date back to the 2nd century BC. Located near Buttala along the Wellawaya-Buttala road, this historic site is linked to legendary battles between princes as mentioned in ancient chronicles. The large stupa stands majestically surrounded by ruins and archaeological remnants, offering visitors a glimpse into Sri Lanka\'s ancient Buddhist civilization. The site has both religious and historical significance.',
                'location' => 'Buttala, Monaragala District',
                'category' => 'temple',
                'highlights' => 'Ancient stupa (2nd century BC), Historical archaeological site, Legendary battles significance, Large stupa structure, Peaceful surroundings',
                'best_time_to_visit' => 'Early morning or evening for peaceful atmosphere. Year-round access. Full moon days (Poya) are special.',
                'how_to_reach' => 'From Wellawaya: Take the road towards Buttala (approximately 25 km). The stupa is located near Buttala town, clearly visible from the main road. Well-accessible by all vehicles.',
                'tips' => 'Remove shoes before entering, Dress modestly, Explore surrounding ruins, Learn about ancient history, Combine with Buttala area visits',
                'latitude' => 6.7500,
                'longitude' => 81.2333,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Handapanagala Tank',
                'slug' => 'handapanagala-tank',
                'description' => 'Handapanagala Tank (Wewa) is an ancient irrigation reservoir that dates back to the reign of King Valagamba (104-88 BC). This historic tank is located approximately 16 km from Wellawaya and offers serene surroundings, abundant birdlife, and peaceful natural setting. The tank is part of Sri Lanka\'s ancient irrigation network and continues to serve agricultural purposes. It\'s an ideal spot for nature lovers, bird watchers, and those seeking tranquility.',
                'location' => 'Handapanagala, Monaragala District',
                'category' => 'nature',
                'highlights' => 'Ancient irrigation tank (2000+ years), Bird watching opportunities, Serene natural setting, Historical significance, Peaceful atmosphere',
                'best_time_to_visit' => 'Early morning (6-9 AM) for bird watching, or late afternoon for sunset views. Best during December to March when water levels are high.',
                'how_to_reach' => 'From Wellawaya: Drive towards Monaragala, then follow signs to Handapanagala village. The tank is approximately 16 km from Wellawaya. Accessible by car or tuk-tuk.',
                'tips' => 'Bring binoculars for bird watching, Best visited early morning, Wear comfortable walking shoes, Bring water and snacks, Photography opportunities',
                'latitude' => 6.7333,
                'longitude' => 81.1667,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Kanabiso Pokuna Raja Maha Viharaya',
                'slug' => 'kanabiso-pokuna-temple',
                'description' => 'Kanabiso Pokuna Raja Maha Viharaya is an archaeological Buddhist temple complex located approximately 12 km from Wellawaya in Handapanagala village. The site features drip-ledged caves (used by Buddhist monks for meditation), scattered stone columns, a ruined stupa, and various archaeological remnants. Recognized as an archaeological monument, this ancient temple offers insights into early Buddhist monastic life and architecture in the region.',
                'location' => 'Handapanagala, Monaragala District',
                'category' => 'temple',
                'highlights' => 'Ancient cave temple, Drip-ledged meditation caves, Archaeological ruins, Stone columns, Historical Buddhist site',
                'best_time_to_visit' => 'Early morning or late afternoon for exploration. Year-round access.',
                'how_to_reach' => 'From Wellawaya: Drive towards Monaragala, then follow signs to Handapanagala village (12 km). The temple is located in the village, accessible by car or tuk-tuk.',
                'tips' => 'Dress modestly, Remove shoes in temple areas, Explore ancient caves, Learn about monastic architecture, Combine with Handapanagala Tank visit',
                'latitude' => 6.7500,
                'longitude' => 81.1833,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Kataragama Sacred City',
                'slug' => 'kataragama-sacred-city',
                'description' => 'Kataragama is one of Sri Lanka\'s most sacred pilgrimage sites, revered by Buddhists, Hindus, Muslims, and indigenous Vedda people. This multi-religious sacred city is located approximately 50 km from Wellawaya and features the Kataragama Temple (Kirivehera Stupa), Kataragama Devalaya, and other religious shrines. The annual Kataragama Perahera festival attracts thousands of devotees. The city is also known for fire-walking ceremonies and spiritual practices.',
                'location' => 'Kataragama, Monaragala District',
                'category' => 'temple',
                'highlights' => 'Multi-religious sacred site, Kataragama Temple, Annual Perahera festival, Fire-walking ceremonies, Spiritual pilgrimage destination',
                'best_time_to_visit' => 'Year-round, but the annual Perahera festival (July/August) is especially significant. Early morning visits are peaceful.',
                'how_to_reach' => 'From Wellawaya: Drive towards Buttala, then continue to Kataragama (approximately 50 km). Well-connected by road. Public buses and tuk-tuks available.',
                'tips' => 'Dress very modestly (white clothing preferred), Remove shoes, Respect religious practices, Visit during festival for cultural experience, Photography may be restricted',
                'latitude' => 6.4167,
                'longitude' => 81.3333,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Yala National Park (Ruhuna)',
                'slug' => 'yala-national-park',
                'description' => 'Yala National Park, also known as Ruhuna National Park, is Sri Lanka\'s most famous and second-largest national park, located approximately 70 km from Wellawaya. The park is renowned for its leopard population and diverse wildlife including elephants, sloth bears, crocodiles, and numerous bird species. The park features varied ecosystems from dense jungles to grasslands and coastal areas, making it a premier wildlife viewing destination in Sri Lanka.',
                'location' => 'Yala, Hambantota District (accessible from Wellawaya/Monaragala)',
                'category' => 'nature',
                'highlights' => 'Leopard sightings, Elephant herds, Diverse wildlife, Bird watching (230+ species), Safari experiences, Coastal areas',
                'best_time_to_visit' => 'February to July for best wildlife sightings. Early morning (6-10 AM) and late afternoon (3-6 PM) are prime safari times.',
                'how_to_reach' => 'From Wellawaya: Drive towards Kataragama, then follow signs to Yala National Park entrance (approximately 70 km). Safari jeeps available for hire at the park entrance.',
                'tips' => 'Book safari in advance, Bring binoculars and camera, Early morning safaris are best, Follow park rules strictly, Wear earth-toned clothing, Bring water and snacks',
                'latitude' => 6.3500,
                'longitude' => 81.3500,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Sithulpawwa Rock Temple',
                'slug' => 'sithulpawwa-rock-temple',
                'description' => 'Sithulpawwa is an ancient rock temple complex dating back to the 2nd century BC, located within Yala National Park. This historic site features cave temples, rock inscriptions, ancient stupas, and meditation caves used by Buddhist monks. The name means "hill of the quiet mind" and the site offers a unique combination of archaeological significance and natural beauty. It\'s accessible via a drive through Yala National Park or from the coastal side.',
                'location' => 'Yala National Park area, Hambantota District',
                'category' => 'temple',
                'highlights' => '2nd-century BC temple, Cave temples and meditation caves, Ancient rock inscriptions, Stupa ruins, Wildlife viewing opportunities',
                'best_time_to_visit' => 'Early morning (before 9 AM) to avoid heat and crowds. Year-round access. Combine with Yala safari.',
                'how_to_reach' => 'From Wellawaya: Drive to Yala area (70 km), then access via Yala National Park or coastal route. Requires travel through or near park boundaries.',
                'tips' => 'Dress modestly, Remove shoes, Bring water, Best visited early morning, Can combine with Yala safari, Photography allowed in designated areas',
                'latitude' => 6.3833,
                'longitude' => 81.3833,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Monaragala Town Viewpoint',
                'slug' => 'monaragala-town-viewpoint',
                'description' => 'Monaragala Town offers a pleasant mountain town experience with scenic viewpoints overlooking the surrounding valleys and hills. The town serves as a gateway to the region\'s attractions and features local markets, temples, and viewpoints. From elevated areas in and around Monaragala, visitors can enjoy panoramic views of the Uva and Eastern Province landscapes, making it a good stopover for scenic photography.',
                'location' => 'Monaragala Town, Monaragala District',
                'category' => 'viewpoint',
                'highlights' => 'Scenic mountain town, Panoramic valley views, Local market experience, Gateway to regional attractions, Photography opportunities',
                'best_time_to_visit' => 'Early morning or late afternoon for best views. Year-round access.',
                'how_to_reach' => 'From Wellawaya: Drive directly to Monaragala town (approximately 30 km). Well-connected by A4 highway. Accessible by all vehicles.',
                'tips' => 'Stop at viewpoints around town, Visit local market, Use as base for regional exploration, Good for photography, Explore local eateries',
                'latitude' => 6.8667,
                'longitude' => 81.3500,
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'name' => 'Buttala Archaeological Sites',
                'slug' => 'buttala-archaeological-sites',
                'description' => 'Buttala and its surrounding areas are rich in archaeological sites, ancient temples, and historical monuments. The region features numerous ancient Buddhist monasteries, cave temples, inscriptions, and ruins dating back to various periods of Sri Lankan history. These sites offer valuable insights into the island\'s ancient civilizations, Buddhist heritage, and architectural developments. Exploring Buttala\'s archaeological landscape provides a comprehensive understanding of the region\'s historical significance.',
                'location' => 'Buttala and surrounding areas, Monaragala District',
                'category' => 'temple',
                'highlights' => 'Multiple archaeological sites, Ancient monasteries, Cave temples, Rock inscriptions, Historical ruins, Rich Buddhist heritage',
                'best_time_to_visit' => 'Early morning or late afternoon for exploration. Year-round access.',
                'how_to_reach' => 'From Wellawaya: Drive to Buttala (approximately 25 km). Multiple archaeological sites are scattered in and around Buttala town. Local guides recommended.',
                'tips' => 'Hire local guide for better understanding, Visit multiple sites in one day, Dress modestly for temple visits, Bring water, Allow full day for exploration',
                'latitude' => 6.7500,
                'longitude' => 81.2500,
                'is_published' => true,
                'published_at' => now(),
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::firstOrCreate(
                ['slug' => $destination['slug']],
                array_merge($destination, ['user_id' => $adminUser->id])
            );
        }

        $this->command->info('Successfully seeded ' . count($destinations) . ' destinations near Wellawaya, Monaragala, and Buttala!');
    }
}
