@extends('admin.layout')

@section('title', 'Create Blog Post')
@section('page-title', 'Create New Blog Post')

@section('content')
<div class="page-header">
    <h1>Create New Blog Post</h1>
    <div class="breadcrumb"><a href="{{ route('admin.blogs.index') }}">Blog Posts</a> / Create</div>
</div>

<div class="card">
    <div class="card-header">
        <h3>Blog Post Information</h3>
    </div>
    <form action="{{ route('admin.blogs.store') }}" method="POST">
        @csrf
        
        <div class="form-group">
            <label class="form-label" for="title">Title *</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ old('title') }}" required>
        </div>
        
        <div class="form-group">
            <label class="form-label" for="slug">Slug</label>
            <input type="text" class="form-control" id="slug" name="slug" value="{{ old('slug') }}" placeholder="auto-generated if left empty">
            <small style="color: var(--text-light);">URL-friendly version of the title. Leave empty to auto-generate.</small>
        </div>
        
        <div class="form-group">
            <label class="form-label" for="excerpt">Excerpt</label>
            <textarea class="form-control" id="excerpt" name="excerpt" rows="3" placeholder="Brief summary of the post">{{ old('excerpt') }}</textarea>
            <small style="color: var(--text-light);">A short summary that appears in blog listings (max 500 characters).</small>
        </div>
        
        <div class="form-group">
            <label class="form-label" for="content">Content *</label>
            <textarea class="form-control" id="content" name="content" rows="15" required>{{ old('content') }}</textarea>
        </div>
        
        <div class="form-group">
            <label class="form-label" for="featured_image">Featured Image URL</label>
            <input type="url" class="form-control" id="featured_image" name="featured_image" value="{{ old('featured_image') }}" placeholder="https://example.com/image.jpg">
            <small style="color: var(--text-light);">URL to the featured image for this blog post.</small>
        </div>
        
        <div class="form-group">
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="is_published" name="is_published" value="1" {{ old('is_published') ? 'checked' : '' }}>
                <label class="form-check-label" for="is_published">Publish this post</label>
            </div>
        </div>
        
        <div class="form-group">
            <label class="form-label" for="published_at">Published At</label>
            <input type="datetime-local" class="form-control" id="published_at" name="published_at" value="{{ old('published_at') }}">
            <small style="color: var(--text-light);">Leave empty to use current date/time when published.</small>
        </div>
        
        <div style="display: flex; gap: 1rem; margin-top: 2rem;">
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-save"></i> Create Post
            </button>
            <a href="{{ route('admin.blogs.index') }}" class="btn btn-secondary">
                <i class="fas fa-times"></i> Cancel
            </a>
        </div>
    </form>
</div>

@push('scripts')
<script>
    // Auto-generate slug from title
    document.getElementById('title').addEventListener('input', function() {
        const slugInput = document.getElementById('slug');
        if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
            const title = this.value;
            const slug = title.toLowerCase()
                .replace(/[^a-z0-9\s-]/g, '')
                .replace(/\s+/g, '-')
                .replace(/-+/g, '-')
                .trim();
            slugInput.value = slug;
            slugInput.dataset.autoGenerated = 'true';
        }
    });

    // Stop auto-generation if user manually edits slug
    document.getElementById('slug').addEventListener('input', function() {
        this.dataset.autoGenerated = 'false';
    });
</script>
@endpush
@endsection
